### ISSUE TITLE
SendNotification authorization: 401 Unauthorized

### ISSUE THREAD

**Issue by silviubogan** [AnbuMani27/Xamarin-Forms-FCM-Notifications#1]
https://github.com/AnbuMani27/Xamarin-Forms-FCM-Notifications/blob/6c401ab85336183802e88aeadca62534819eee17/XF_FCM%20Notifications/FCMSample/FCMSample/MainPage.xaml.cs#L60

Where I can find my API key? I tried to find my own API key in my own `google-services.json`, and it is in another format than the one used in your associated blog posts. I've tried with my own API key (`client.api_key.current_key`) finally, but I still get an error.

The HTTP response as shown in the VS debugger:

https://github.com/AnbuMani27/Xamarin-Forms-FCM-Notifications/blob/6c401ab85336183802e88aeadca62534819eee17/XF_FCM%20Notifications/FCMSample/FCMSample/MainPage.xaml.cs#L65

is

```
{StatusCode: 401, ReasonPhrase: 'Unauthorized', Version: 1.1, Content: System.Net.Http.StreamContent, Headers:
{
  Accept-Ranges: none
  Alt-Svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000
  Cache-Control: max-age=0, private
  Date: Thu, 30 Jan 2020 11:15:39 GMT
  Server: GSE
  Transfer-Encoding: chunked
  Vary: Accept-Encoding
  X-Android-Received-Millis: 1580382937838
  X-Android-Response-Source: NETWORK 401
  X-Android-Selected-Protocol: http/1.1
  X-Android-Sent-Millis: 1580382937628
  X-Content-Type-Options: nosniff
  X-Frame-Options: SAMEORIGIN
  X-XSS-Protection: 1; mode=block
  Content-Type: text/html; charset=UTF-8
  Expires: Thu, 30 Jan 2020 11:15:39 GMT
}}
```

When using the cloned repo, this line's condition:

https://github.com/AnbuMani27/Xamarin-Forms-FCM-Notifications/blob/6c401ab85336183802e88aeadca62534819eee17/XF_FCM%20Notifications/FCMSample/FCMSample/MainPage.xaml.cs#L23

is `false`.

Currently I am in the step of running an app with the correct `google-services.json` file. Google tells me:

> # Run your app to verify installation
> Checking if the app has communicated with our servers. You may need to uninstall and reinstall your app.

And a spinner is shown below.

It would be great if you could update this repository with a more current version of Xamarin.Forms and of the dependencies.

Thank you!

**Comment by AnbuMani27** [comment]
Hi @silviubogan, I hope you created the new project in the firebase console.  In that console go to **Project Settings=> Cloud Messaging =>Server key** [This is your API KEY]

More details please check given below Article :

https://xmonkeys360.com/2019/12/08/xamarin-forms-fcm-setup-configuration-part-i/

https://xmonkeys360.com/2019/12/09/fcm-configuration-in-xamarin-forms-part-ii/

**Comment by AnbuMani27** [comment]
@silviubogan Once Cloned this package just change the **google-services.json** [Yours]

**Comment by silviubogan** [comment]
This screen seems to last forever:

![chrome_2020-01-30_14-52-21](https://user-images.githubusercontent.com/198924/73451385-2c7cdc80-4370-11ea-89e3-e91770873ed8.png)

and from this screen I have chosen the thing marked with a red arrow (the blurred code):

![2020-01-30_14-49-46](https://user-images.githubusercontent.com/198924/73452135-eb85c780-4371-11ea-8b11-bc118e58ff8f.png)

I've put that blurred code into this line as indicated:

https://github.com/AnbuMani27/Xamarin-Forms-FCM-Notifications/blob/917b4f866814a30cd6ccffc64c9bd7224940838c/XF_FCM%20Notifications/FCMSample/FCMSample/MainPage.xaml.cs#L60

I also did this for the `Legacy server key` from the image above.

The result is the same as in the first screenshot in this message.

I will try to debug further.

Thank you.

**Comment by AnbuMani27** [comment]
Hi @silviubogan, Don't forgot to change **google-services.json** file AND AndroidManifest.xml settings.

**Comment by silviubogan** [comment]
Please forgive me, I am a beginner. What should I change in the AndroidManifest.xml file?

Thank you.

**Comment by syahman** [comment]
hi,im having same problem to run example code. is it true if  xamarin form cant read the settings in mainpage codebehind ? or public override void OnTokenRefresh() on android project  never executed ? 

var FCMToken = Application.Current.Properties.Keys.Contains("Fcmtocken");

also please take a look here[https://github.com/MicrosoftDocs/xamarin-docs/issues/681](https://github.com/MicrosoftDocs/xamarin-docs/issues/681)

**Comment by AnbuMani27** [comment]
> hi,im having same problem to run example code. is it true if  xamarin form cant read the settings in mainpage codebehind ? or public override void OnTokenRefresh() on android project  never executed ?
> var FCMToken = Application.Current.Properties.Keys.Contains("Fcmtocken");
> also please take a look hereMicrosoftDocs/xamarin-docs#681

Hi @syahman, Did you written given below code in MainActivity.cs  
FirebaseApp.InitializeApp(this);

**Comment by AnbuMani27** [comment]
> OnTokenRefresh()



> hi,im having same problem to run example code. is it true if  xamarin form cant read the settings in mainpage codebehind ? or public override void OnTokenRefresh() on android project  never executed ?
> var FCMToken = Application.Current.Properties.Keys.Contains("Fcmtocken");
> also please take a look hereMicrosoftDocs/xamarin-docs#681
> 
> Hi @syahman, Did you written given below code in MainActivity.cs
> FirebaseApp.InitializeApp(this);

OnTokenRefresh(); This method not executed for the first time, Suppose if you need another token which means you should call this method.

**Comment by AnbuMani27** [comment]
> Please forgive me, I am a beginner. What should I change in the AndroidManifest.xml file?
> Thank you.

Please Check my AndroidManifest.XML

**Comment by syahman** [comment]
@AnbuMani27 glad it working now. thank you 

adding this on MainActivity.cs 
FirebaseApp.InitializeApp(this);

**Comment by silviubogan** [comment]
@AnbuMani27 I replaced `${applicationId}` with `FCMSample` in the AndroidManifest.xml and the same problem occurs (should I have replaced it with something else?). [Here](https://gist.github.com/silviubogan/c8d45b72c5a0e16f0b1f89dae129f764) is what is shown in the Output pane in VS after clicking Send Notifications button (which shows an alert that the notifications were actually sent, but I do not get any notification actually: I've waited a few minutes).

The `FirebaseApp.InitializeApp(this);` is already there, in my MainActivity.cs as cloned from this repo.

The issue is not urgent for me.

Thank you for all your effort.

**Comment by AnbuMani27** [comment]
> @AnbuMani27 I replaced `${applicationId}` with `FCMSample` in the AndroidManifest.xml and the same problem occurs (should I have replaced it with something else?). [Here](https://gist.github.com/silviubogan/c8d45b72c5a0e16f0b1f89dae129f764) is what is shown in the Output pane in VS after clicking Send Notifications button (which shows an alert that the notifications were actually sent, but I do not get any notification actually: I've waited a few minutes).
> 
> The `FirebaseApp.InitializeApp(this);` is already there, in my MainActivity.cs as cloned from this repo.
> 
> The issue is not urgent for me.
> 
> Thank you for all your effort.

Hi @silviubogan, Did you get FCM token?

**Comment by silviubogan** [comment]
@AnbuMani27  Yes, in the output posted above, [here](https://gist.github.com/silviubogan/c8d45b72c5a0e16f0b1f89dae129f764#file-output-txt-L1987-L1988).

Thank you.

**Comment by AnbuMani27** [comment]
> @AnbuMani27  Yes, in the output posted above, here.
> Thank you.

Everything right :-) Next please try given below steps, 

1.Goto => https://console.firebase.google.com/u/0/project/fcmsample-96587/notification/compose
2. Send the Notifications Manually with your mobile generated token, Please find the image for sample


![FCM](https://user-images.githubusercontent.com/23030578/73671033-41d76b00-46d0-11ea-84b6-bedec35d4c73.JPG)

**Comment by silviubogan** [comment]
@AnbuMani27  Due to other priorities, I abandoned this "quest". I am sorry for stealing your time.

Thank you!
