### ISSUE TITLE
Need some details information on FCM

### ISSUE THREAD

**Issue by JayramJai** [AnbuMani27/Xamarin-Forms-FCM-Notifications#2]
1. I downloaded your sample and run it its working great.
2. When i try to build my sample of my own and i pushed my message from firebase also working great.
3. I want to know, how it is really working. is it only with google json file or do i need to add the server key in the project?
4. How can i connect with you?

**Comment by AnbuMani27** [comment]
Hi @JayramJai Thanks :-)

Yes, you need to add both JSON File and API server Key in your project.

Please reach out me: anbu@anbumani.dev
